-- Items UDB 365 10.5 to Chrono
ALTER TABLE `items` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci,
ROW_FORMAT=Dynamic;
ALTER TABLE `items` DROP INDEX `items_index`;
ALTER TABLE `items` DROP INDEX `idx_name`;
ALTER TABLE `items` MODIFY COLUMN `entry`  int(255) UNSIGNED NOT NULL DEFAULT 0 FIRST ;
ALTER TABLE `items` MODIFY COLUMN `class`  int(30) NOT NULL DEFAULT 0 AFTER `entry`;
ALTER TABLE `items` MODIFY COLUMN `subclass`  int(30) NOT NULL DEFAULT 0 AFTER `class`;
ALTER TABLE `items` CHANGE COLUMN `unk0` `field4`  int(10) NOT NULL DEFAULT '-1' AFTER `subclass`;
ALTER TABLE `items` CHANGE COLUMN `name` `name1`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL AFTER `field4`;
ALTER TABLE `items` ADD COLUMN `name2`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '' AFTER `name1`;
ALTER TABLE `items` ADD COLUMN `name3`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '' AFTER `name2`;
ALTER TABLE `items` ADD COLUMN `name4`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '' AFTER `name3`;
ALTER TABLE `items` MODIFY COLUMN `displayid`  int(70) UNSIGNED NOT NULL DEFAULT 0 AFTER `name4`;
ALTER TABLE `items` CHANGE COLUMN `Quality` `quality`  int(30) NOT NULL DEFAULT 0 AFTER `displayid`;
ALTER TABLE `items` CHANGE COLUMN `Flags` `flags`  int(30) NOT NULL DEFAULT 0 AFTER `quality`;
ALTER TABLE `items` DROP COLUMN `BuyCount`;
ALTER TABLE `items` CHANGE COLUMN `BuyPrice` `buyprice`  int(30) NOT NULL DEFAULT 0 AFTER `flags`;
ALTER TABLE `items` CHANGE COLUMN `SellPrice` `sellprice`  int(30) NOT NULL DEFAULT 0 AFTER `buyprice`;
ALTER TABLE `items` CHANGE COLUMN `InventoryType` `inventorytype`  int(30) NOT NULL DEFAULT 0 AFTER `sellprice`;
ALTER TABLE `items` CHANGE COLUMN `AllowableClass` `allowableclass`  int(30) NOT NULL DEFAULT 0 AFTER `inventorytype`;
ALTER TABLE `items` CHANGE COLUMN `AllowableRace` `allowablerace`  int(30) NOT NULL DEFAULT 0 AFTER `allowableclass`;
ALTER TABLE `items` CHANGE COLUMN `ItemLevel` `itemlevel`  int(30) NOT NULL DEFAULT 0 AFTER `allowablerace`;
ALTER TABLE `items` CHANGE COLUMN `RequiredLevel` `requiredlevel`  int(30) NOT NULL DEFAULT 0 AFTER `itemlevel`;
ALTER TABLE `items` MODIFY COLUMN `RequiredSkill`  int(30) NOT NULL DEFAULT 0 AFTER `requiredlevel`;
ALTER TABLE `items` MODIFY COLUMN `RequiredSkillRank`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredSkill`;
ALTER TABLE `items` CHANGE COLUMN `requiredspell` `RequiredSkillSubRank`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredSkillRank`;
ALTER TABLE `items` CHANGE COLUMN `requiredhonorrank` `RequiredPlayerRank1`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredSkillSubRank`;
ALTER TABLE `items` CHANGE COLUMN `RequiredCityRank` `RequiredPlayerRank2`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredPlayerRank1`;
ALTER TABLE `items` CHANGE COLUMN `RequiredReputationFaction` `RequiredFaction`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredPlayerRank2`;
ALTER TABLE `items` CHANGE COLUMN `RequiredReputationRank` `RequiredFactionStanding`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredFaction`;
ALTER TABLE `items` CHANGE COLUMN `maxcount` `Unique`  int(30) NOT NULL DEFAULT 0 AFTER `RequiredFactionStanding`;
ALTER TABLE `items` DROP COLUMN `spellppmRate_1`;
ALTER TABLE `items` DROP COLUMN `spellppmRate_2`;
ALTER TABLE `items` DROP COLUMN `spellppmRate_3`;
ALTER TABLE `items` DROP COLUMN `spellppmRate_4`;
ALTER TABLE `items` DROP COLUMN `spellppmRate_5`;
ALTER TABLE `items` CHANGE COLUMN `stackable` `maxcount`  int(30) NOT NULL DEFAULT 0 AFTER `Unique`;
ALTER TABLE `items` MODIFY COLUMN `ContainerSlots`  int(30) NOT NULL DEFAULT 0 AFTER `maxcount`;
ALTER TABLE `items` MODIFY COLUMN `stat_type1`  int(30) NOT NULL DEFAULT 0 AFTER `ContainerSlots`;
ALTER TABLE `items` MODIFY COLUMN `stat_value1`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type1`;
ALTER TABLE `items` MODIFY COLUMN `stat_type2`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value1`;
ALTER TABLE `items` MODIFY COLUMN `stat_value2`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type2`;
ALTER TABLE `items` MODIFY COLUMN `stat_type3`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value2`;
ALTER TABLE `items` MODIFY COLUMN `stat_value3`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type3`;
ALTER TABLE `items` MODIFY COLUMN `stat_type4`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value3`;
ALTER TABLE `items` MODIFY COLUMN `stat_value4`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type4`;
ALTER TABLE `items` MODIFY COLUMN `stat_type5`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value4`;
ALTER TABLE `items` MODIFY COLUMN `stat_value5`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type5`;
ALTER TABLE `items` MODIFY COLUMN `stat_type6`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value5`;
ALTER TABLE `items` MODIFY COLUMN `stat_value6`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type6`;
ALTER TABLE `items` MODIFY COLUMN `stat_type7`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value6`;
ALTER TABLE `items` MODIFY COLUMN `stat_value7`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type7`;
ALTER TABLE `items` MODIFY COLUMN `stat_type8`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value7`;
ALTER TABLE `items` MODIFY COLUMN `stat_value8`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type8`;
ALTER TABLE `items` MODIFY COLUMN `stat_type9`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value8`;
ALTER TABLE `items` MODIFY COLUMN `stat_value9`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type9`;
ALTER TABLE `items` MODIFY COLUMN `stat_type10`  int(30) NOT NULL DEFAULT 0 AFTER `stat_value9`;
ALTER TABLE `items` MODIFY COLUMN `stat_value10`  int(30) NOT NULL DEFAULT 0 AFTER `stat_type10`;
ALTER TABLE `items` MODIFY COLUMN `dmg_type1`  int(30) NOT NULL DEFAULT 0 AFTER `dmg_max1`;
ALTER TABLE `items` MODIFY COLUMN `dmg_type2`  int(30) NOT NULL DEFAULT 0 AFTER `dmg_max2`;
ALTER TABLE `items` MODIFY COLUMN `dmg_type3`  int(30) NOT NULL DEFAULT 0 AFTER `dmg_max3`;
ALTER TABLE `items` MODIFY COLUMN `dmg_type4`  int(30) NOT NULL DEFAULT 0 AFTER `dmg_max4`;
ALTER TABLE `items` MODIFY COLUMN `dmg_type5`  int(30) NOT NULL DEFAULT 0 AFTER `dmg_max5`;
ALTER TABLE `items` MODIFY COLUMN `armor`  int(30) NOT NULL DEFAULT 0 AFTER `dmg_type5`;
ALTER TABLE `items` MODIFY COLUMN `holy_res`  int(30) NOT NULL DEFAULT 0 AFTER `armor`;
ALTER TABLE `items` MODIFY COLUMN `fire_res`  int(30) NOT NULL DEFAULT 0 AFTER `holy_res`;
ALTER TABLE `items` MODIFY COLUMN `nature_res`  int(30) NOT NULL DEFAULT 0 AFTER `fire_res`;
ALTER TABLE `items` MODIFY COLUMN `frost_res`  int(30) NOT NULL DEFAULT 0 AFTER `nature_res`;
ALTER TABLE `items` MODIFY COLUMN `shadow_res`  int(30) NOT NULL DEFAULT 0 AFTER `frost_res`;
ALTER TABLE `items` MODIFY COLUMN `arcane_res`  int(30) NOT NULL DEFAULT 0 AFTER `shadow_res`;
ALTER TABLE `items` MODIFY COLUMN `delay`  int(30) NOT NULL DEFAULT 0 AFTER `arcane_res`;
ALTER TABLE `items` MODIFY COLUMN `ammo_type`  int(30) NOT NULL DEFAULT 0 AFTER `delay`;
ALTER TABLE `items` CHANGE COLUMN `RangedModRange` `range`  float NOT NULL DEFAULT 0 AFTER `ammo_type`; 
ALTER TABLE `items` MODIFY COLUMN `spellid_1`  int(30) NOT NULL DEFAULT 0 AFTER `range`;
ALTER TABLE `items` MODIFY COLUMN `spelltrigger_1`  int(30) NOT NULL DEFAULT 0 AFTER `spellid_1`;
ALTER TABLE `items` MODIFY COLUMN `spellcharges_1`  int(30) NOT NULL DEFAULT 0 AFTER `spelltrigger_1`;
ALTER TABLE `items` MODIFY COLUMN `spellcooldown_1`  int(30) NOT NULL DEFAULT 0 AFTER `spellcharges_1`;
ALTER TABLE `items` MODIFY COLUMN `spellcategory_1`  int(30) NOT NULL DEFAULT 0 AFTER `spellcooldown_1`;
ALTER TABLE `items` MODIFY COLUMN `spellcategorycooldown_1`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategory_1`;
ALTER TABLE `items` MODIFY COLUMN `spellid_2`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategorycooldown_1`;
ALTER TABLE `items` MODIFY COLUMN `spelltrigger_2`  int(30) NOT NULL DEFAULT 0 AFTER `spellid_2`;
ALTER TABLE `items` MODIFY COLUMN `spellcharges_2`  int(30) NOT NULL DEFAULT 0 AFTER `spelltrigger_2`;
ALTER TABLE `items` MODIFY COLUMN `spellcooldown_2`  int(30) NOT NULL DEFAULT 0 AFTER `spellcharges_2`;
ALTER TABLE `items` MODIFY COLUMN `spellcategory_2`  int(30) NOT NULL DEFAULT 0 AFTER `spellcooldown_2`;
ALTER TABLE `items` MODIFY COLUMN `spellcategorycooldown_2`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategory_2`;
ALTER TABLE `items` MODIFY COLUMN `spellid_3`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategorycooldown_2`;
ALTER TABLE `items` MODIFY COLUMN `spelltrigger_3`  int(30) NOT NULL DEFAULT 0 AFTER `spellid_3`;
ALTER TABLE `items` MODIFY COLUMN `spellcharges_3`  int(30) NOT NULL DEFAULT 0 AFTER `spelltrigger_3`;
ALTER TABLE `items` MODIFY COLUMN `spellcooldown_3`  int(30) NOT NULL DEFAULT 0 AFTER `spellcharges_3`;
ALTER TABLE `items` MODIFY COLUMN `spellcategory_3`  int(30) NOT NULL DEFAULT 0 AFTER `spellcooldown_3`;
ALTER TABLE `items` MODIFY COLUMN `spellcategorycooldown_3`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategory_3`;
ALTER TABLE `items` MODIFY COLUMN `spellid_4`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategorycooldown_3`;
ALTER TABLE `items` MODIFY COLUMN `spelltrigger_4`  int(30) NOT NULL DEFAULT 0 AFTER `spellid_4`;
ALTER TABLE `items` MODIFY COLUMN `spellcharges_4`  int(30) NOT NULL DEFAULT 0 AFTER `spelltrigger_4`;
ALTER TABLE `items` MODIFY COLUMN `spellcooldown_4`  int(30) NOT NULL DEFAULT 0 AFTER `spellcharges_4`;
ALTER TABLE `items` MODIFY COLUMN `spellcategory_4`  int(30) NOT NULL DEFAULT 0 AFTER `spellcooldown_4`;
ALTER TABLE `items` MODIFY COLUMN `spellcategorycooldown_4`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategory_4`;
ALTER TABLE `items` MODIFY COLUMN `spellid_5`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategorycooldown_4`;
ALTER TABLE `items` MODIFY COLUMN `spelltrigger_5`  int(30) NOT NULL DEFAULT 0 AFTER `spellid_5`;
ALTER TABLE `items` MODIFY COLUMN `spellcharges_5`  int(30) NOT NULL DEFAULT 0 AFTER `spelltrigger_5`;
ALTER TABLE `items` MODIFY COLUMN `spellcooldown_5`  int(30) NOT NULL DEFAULT 0 AFTER `spellcharges_5`;
ALTER TABLE `items` MODIFY COLUMN `spellcategory_5`  int(30) NOT NULL DEFAULT 0 AFTER `spellcooldown_5`;
ALTER TABLE `items` MODIFY COLUMN `spellcategorycooldown_5`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategory_5`;
ALTER TABLE `items` MODIFY COLUMN `bonding`  int(30) NOT NULL DEFAULT 0 AFTER `spellcategorycooldown_5`;
ALTER TABLE `items` MODIFY COLUMN `description`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '' AFTER `bonding`;
ALTER TABLE `items` CHANGE COLUMN `PageText` `page_id`  int(30) NOT NULL DEFAULT 0 AFTER `description`;
ALTER TABLE `items` CHANGE COLUMN `LanguageID` `page_language`  int(30) NOT NULL DEFAULT 0 AFTER `page_id`;
ALTER TABLE `items` CHANGE COLUMN `PageMaterial` `page_material`  int(30) NOT NULL DEFAULT 0 AFTER `page_language`;
ALTER TABLE `items` CHANGE COLUMN `startquest` `quest_id`  int(30) NOT NULL DEFAULT 0 AFTER `page_material`;
ALTER TABLE `items` CHANGE COLUMN `lockid` `lock_id`  int(30) NOT NULL DEFAULT 0 AFTER `quest_id`;
ALTER TABLE `items` CHANGE COLUMN `Material` `lock_material`  int(30) NOT NULL DEFAULT 0 AFTER `lock_id`;
ALTER TABLE `items` CHANGE COLUMN `sheath` `sheathID`  int(30) NOT NULL DEFAULT 0 AFTER `lock_material`;
ALTER TABLE `items` CHANGE COLUMN `RandomProperty` `randomprop`  int(30) NOT NULL DEFAULT 0 AFTER `sheathID`;
ALTER TABLE `items` CHANGE COLUMN `RandomSuffix` `unk203_1`  int(11) NOT NULL DEFAULT 0 AFTER `randomprop`;
ALTER TABLE `items` MODIFY COLUMN `block`  int(30) NOT NULL DEFAULT 0 AFTER `unk203_1`;
ALTER TABLE `items` MODIFY COLUMN `itemset`  int(30) NOT NULL DEFAULT 0 AFTER `block`;
ALTER TABLE `items` MODIFY COLUMN `MaxDurability`  int(30) NOT NULL DEFAULT 0 AFTER `itemset`;
ALTER TABLE `items` CHANGE COLUMN `area` `ZoneNameID`  int(30) NOT NULL DEFAULT 0 AFTER `MaxDurability`;
ALTER TABLE `items` CHANGE COLUMN `Map` `mapid`  int(30) NULL DEFAULT NULL AFTER `ZoneNameID`;
ALTER TABLE `items` CHANGE COLUMN `BagFamily` `bagfamily`  int(30) NOT NULL DEFAULT 0 AFTER `mapid`;
ALTER TABLE `items` MODIFY COLUMN `TotemCategory`  int(30) NULL DEFAULT NULL AFTER `bagfamily`;
ALTER TABLE `items` CHANGE COLUMN `socketColor_1` `socket_color_1`  int(30) NULL DEFAULT NULL AFTER `TotemCategory`;
ALTER TABLE `items` CHANGE COLUMN `socketContent_1` `unk201_3`  int(30) NOT NULL DEFAULT 0 AFTER `socket_color_1`;
ALTER TABLE `items` CHANGE COLUMN `socketColor_2` `socket_color_2`  int(30) NULL DEFAULT NULL AFTER `unk201_3`;
ALTER TABLE `items` CHANGE COLUMN `socketContent_2` `unk201_5`  int(30) NOT NULL DEFAULT 0 AFTER `socket_color_2`;
ALTER TABLE `items` CHANGE COLUMN `socketColor_3` `socket_color_3`  int(30) NULL DEFAULT NULL AFTER `unk201_5`;
ALTER TABLE `items` CHANGE COLUMN `socketContent_3` `unk201_7`  int(30) NOT NULL DEFAULT 0 AFTER `socket_color_3`;
ALTER TABLE `items` CHANGE COLUMN `socketBonus` `socket_bonus`  int(30) NULL DEFAULT NULL AFTER `unk201_7`;
ALTER TABLE `items` MODIFY COLUMN `GemProperties`  int(30) NULL DEFAULT NULL AFTER `socket_bonus`;
ALTER TABLE `items` CHANGE COLUMN `RequiredDisenchantSkill` `ReqDisenchantSkill`  int(30) NOT NULL DEFAULT '-1' AFTER `GemProperties`;
ALTER TABLE `items` ADD COLUMN `unk2`  int(30) NOT NULL DEFAULT 0 AFTER `ReqDisenchantSkill`;
ALTER TABLE `items` DROP COLUMN `ArmorDamageModifier`;
ALTER TABLE `items` DROP COLUMN `ScriptName`;
ALTER TABLE `items` DROP COLUMN `DisenchantID`;
ALTER TABLE `items` DROP COLUMN `FoodType`;
ALTER TABLE `items` DROP COLUMN `minMoneyLoot`;
ALTER TABLE `items` DROP COLUMN `maxMoneyLoot`;
ALTER TABLE `items` DROP COLUMN `Duration`;
CREATE UNIQUE INDEX `entry` ON `items`(`entry`) USING BTREE ;


 