/****************************************************************************
 *
 * Spell System
 * Copyright (c) 2009 Forsaken Gaming
 * Parsed by Sphere
 * Version Parsed: 5875
 * Date Parsed: March 17th, 2010
 *
 */

#ifndef _SPELLFAILURE_H
#define _SPELLFAILURE_H

enum SpellCastError
{
	SPELL_FAILED_AFFECTING_COMBAT                                = 0,
	SPELL_FAILED_ALREADY_AT_FULL_HEALTH                          = 1,
	SPELL_FAILED_ALREADY_AT_FULL_POWER                           = 2,
	SPELL_FAILED_ALREADY_BEING_TAMED                             = 3,
	SPELL_FAILED_ALREADY_HAVE_CHARM                              = 4,
	SPELL_FAILED_ALREADY_HAVE_SUMMON                             = 5,
	SPELL_FAILED_ALREADY_OPEN                                    = 6,
	SPELL_FAILED_AURA_BOUNCED                                    = 7,
	SPELL_FAILED_AUTOTRACK_INTERRUPTED                           = 8,
	SPELL_FAILED_BAD_IMPLICIT_TARGETS                            = 9,
	SPELL_FAILED_BAD_TARGETS                                     = 10,
	SPELL_FAILED_CANT_BE_CHARMED                                 = 11,
	SPELL_FAILED_CANT_BE_DISENCHANTED                            = 12,
	SPELL_FAILED_CANT_BE_PROSPECTED                              = 13,
	SPELL_FAILED_CANT_CAST_ON_TAPPED                             = 14,
	SPELL_FAILED_CANT_DUEL_WHILE_INVISIBLE                       = 15,
	SPELL_FAILED_CANT_DUEL_WHILE_STEALTHED                       = 16,
	SPELL_FAILED_CANT_STEALTH                                    = 17,
	SPELL_FAILED_CASTER_AURASTATE                                = 18,
	SPELL_FAILED_CASTER_DEAD                                     = 19,
	SPELL_FAILED_CHARMED                                         = 20,
	SPELL_FAILED_CHEST_IN_USE                                    = 21,
	SPELL_FAILED_CONFUSED                                        = 22,
	SPELL_FAILED_DONT_REPORT                                     = 23,
	SPELL_FAILED_EQUIPPED_ITEM                                   = 24,
	SPELL_FAILED_EQUIPPED_ITEM_CLASS                             = 25,
	SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND                    = 26,
	SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND                     = 27,
	SPELL_FAILED_ERROR                                           = 28,
	SPELL_FAILED_FIZZLE                                          = 29,
	SPELL_FAILED_FLEEING                                         = 30,
	SPELL_FAILED_FOOD_LOWLEVEL                                   = 31,
	SPELL_FAILED_HIGHLEVEL                                       = 32,
	SPELL_FAILED_HUNGER_SATIATED                                 = 33,
	SPELL_FAILED_IMMUNE                                          = 34,
	SPELL_FAILED_INTERRUPTED                                     = 35,
	SPELL_FAILED_INTERRUPTED_COMBAT                              = 36,
	SPELL_FAILED_ITEM_ALREADY_ENCHANTED                          = 37,
	SPELL_FAILED_ITEM_GONE                                       = 38,
	SPELL_FAILED_ITEM_NOT_FOUND                                  = 39,
	SPELL_FAILED_ITEM_NOT_READY                                  = 40,
	SPELL_FAILED_LEVEL_REQUIREMENT                               = 41,
	SPELL_FAILED_LINE_OF_SIGHT                                   = 42,
	SPELL_FAILED_LOWLEVEL                                        = 43,
	SPELL_FAILED_LOW_CASTLEVEL                                   = 44,
	SPELL_FAILED_MAINHAND_EMPTY                                  = 45,
	SPELL_FAILED_MOVING                                          = 46,
	SPELL_FAILED_NEED_AMMO                                       = 47,
	SPELL_FAILED_NEED_AMMO_POUCH                                 = 48,
	SPELL_FAILED_NEED_EXOTIC_AMMO                                = 49,
	SPELL_FAILED_NOPATH                                          = 50,
	SPELL_FAILED_NOT_BEHIND                                      = 51,
	SPELL_FAILED_NOT_FISHABLE                                    = 52,
	SPELL_FAILED_NOT_HERE                                        = 53,
	SPELL_FAILED_NOT_INFRONT                                     = 54,
	SPELL_FAILED_NOT_IN_CONTROL                                  = 55,
	SPELL_FAILED_NOT_KNOWN                                       = 56,
	SPELL_FAILED_NOT_MOUNTED                                     = 57,
	SPELL_FAILED_NOT_ON_TAXI                                     = 58,
	SPELL_FAILED_NOT_ON_TRANSPORT                                = 59,
	SPELL_FAILED_NOT_READY                                       = 60,
	SPELL_FAILED_NOT_SHAPESHIFT                                  = 61,
	SPELL_FAILED_NOT_STANDING                                    = 62,
	SPELL_FAILED_NOT_TRADEABLE                                   = 63,
	SPELL_FAILED_NOT_TRADING                                     = 64,
	SPELL_FAILED_NOT_UNSHEATHED                                  = 65,
	SPELL_FAILED_NOT_WHILE_GHOST                                 = 66,
	SPELL_FAILED_NO_AMMO                                         = 67,
	SPELL_FAILED_NO_CHARGES_REMAIN                               = 68,
	SPELL_FAILED_NO_CHAMPION                                     = 69,
	SPELL_FAILED_NO_COMBO_POINTS                                 = 70,
	SPELL_FAILED_NO_DUELING                                      = 71,
	SPELL_FAILED_NO_ENDURANCE                                    = 72,
	SPELL_FAILED_NO_FISH                                         = 73,
	SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED                     = 74,
	SPELL_FAILED_NO_MOUNTS_ALLOWED                               = 75,
	SPELL_FAILED_NO_PET                                          = 76,
	SPELL_FAILED_NO_POWER                                        = 77,
	SPELL_FAILED_NOTHING_TO_DISPEL                               = 78,
	SPELL_FAILED_NOTHING_TO_STEAL                                = 79,
	SPELL_FAILED_ONLY_ABOVEWATER                                 = 80,
	SPELL_FAILED_ONLY_DAYTIME                                    = 81,
	SPELL_FAILED_ONLY_INDOORS                                    = 82,
	SPELL_FAILED_ONLY_MOUNTED                                    = 83,
	SPELL_FAILED_ONLY_NIGHTTIME                                  = 84,
	SPELL_FAILED_ONLY_OUTDOORS                                   = 85,
	SPELL_FAILED_ONLY_SHAPESHIFT                                 = 86,
	SPELL_FAILED_ONLY_STEALTHED                                  = 87,
	SPELL_FAILED_ONLY_UNDERWATER                                 = 88,
	SPELL_FAILED_OUT_OF_RANGE                                    = 89,
	SPELL_FAILED_PACIFIED                                        = 90,
	SPELL_FAILED_POSSESSED                                       = 91,
	SPELL_FAILED_REAGENTS                                        = 92,
	SPELL_FAILED_REQUIRES_AREA                                   = 93,
	SPELL_FAILED_REQUIRES_SPELL_FOCUS                            = 94,
	SPELL_FAILED_ROOTED                                          = 95,
	SPELL_FAILED_SILENCED                                        = 96,
	SPELL_FAILED_SPELL_IN_PROGRESS                               = 97,
	SPELL_FAILED_SPELL_LEARNED                                   = 98,
	SPELL_FAILED_SPELL_UNAVAILABLE                               = 99,
	SPELL_FAILED_STUNNED                                         = 100,
	SPELL_FAILED_TARGETS_DEAD                                    = 101,
	SPELL_FAILED_TARGET_AFFECTING_COMBAT                         = 102,
	SPELL_FAILED_TARGET_AURASTATE                                = 103,
	SPELL_FAILED_TARGET_DUELING                                  = 104,
	SPELL_FAILED_TARGET_ENEMY                                    = 105,
	SPELL_FAILED_TARGET_ENRAGED                                  = 106,
	SPELL_FAILED_TARGET_FRIENDLY                                 = 107,
	SPELL_FAILED_TARGET_IN_COMBAT                                = 108,
	SPELL_FAILED_TARGET_IS_PLAYER                                = 109,
	SPELL_FAILED_TARGET_NOT_DEAD                                 = 110,
	SPELL_FAILED_TARGET_NOT_IN_PARTY                             = 111,
	SPELL_FAILED_TARGET_NOT_LOOTED                               = 112,
	SPELL_FAILED_TARGET_NOT_PLAYER                               = 113,
	SPELL_FAILED_TARGET_NO_POCKETS                               = 114,
	SPELL_FAILED_TARGET_NO_WEAPONS                               = 115,
	SPELL_FAILED_TARGET_UNSKINNABLE                              = 116,
	SPELL_FAILED_THIRST_SATIATED                                 = 117,
	SPELL_FAILED_TOO_CLOSE                                       = 118,
	SPELL_FAILED_TOO_MANY_OF_ITEM                                = 119,
	SPELL_FAILED_TOTEMS                                          = 120,
	SPELL_FAILED_TRAINING_POINTS                                 = 121,
	SPELL_FAILED_TRY_AGAIN                                       = 122,
	SPELL_FAILED_UNIT_NOT_BEHIND                                 = 123,
	SPELL_FAILED_UNIT_NOT_INFRONT                                = 124,
	SPELL_FAILED_WRONG_PET_FOOD                                  = 125,
	SPELL_FAILED_NOT_WHILE_FATIGUED                              = 126,
	SPELL_FAILED_TARGET_NOT_IN_INSTANCE                          = 127,
	SPELL_FAILED_NOT_WHILE_TRADING                               = 128,
	SPELL_FAILED_TARGET_NOT_IN_RAID                              = 129,
	SPELL_FAILED_DISENCHANT_WHILE_LOOTING                        = 130,
	SPELL_FAILED_PROSPECT_WHILE_LOOTING                          = 131,
	SPELL_FAILED_PROSPECT_NEED_MORE                              = 132,
	SPELL_FAILED_TARGET_FREEFORALL                               = 133,
	SPELL_FAILED_NO_EDIBLE_CORPSES                               = 134,
	SPELL_FAILED_ONLY_BATTLEGROUNDS                              = 135,
	SPELL_FAILED_TARGET_NOT_GHOST                                = 136,
	SPELL_FAILED_TOO_MANY_SKILLS                                 = 137,
	SPELL_FAILED_TRANSFORM_UNUSABLE                              = 138,
	SPELL_FAILED_WRONG_WEATHER                                   = 139,
	SPELL_FAILED_DAMAGE_IMMUNE                                   = 140,
	SPELL_FAILED_PREVENTED_BY_MECHANIC                           = 141,
	SPELL_FAILED_PLAY_TIME                                       = 142,
	SPELL_FAILED_REPUTATION                                      = 143,
	SPELL_FAILED_MIN_SKILL                                       = 144,
	SPELL_FAILED_UNKNOWN                                         = 145,
	SPELL_CANCAST_OK                            				 = 255,
};

#endif

